Add escapes to string quotes
sql-formatter-org/sql-formatter pull request #354
Opened 2022-07-28 02:08 UTC by inferrinizzard

- adds support for specific escapes for string types
- adds tests for all quote types + prefixes + escapes
- updates some string regex
- adds string escapes for all languages
- moves string types to class static members

2022-07-28 12:10 UTC, nene requested changes
Thanks for the effort on this.

The escaping implementation looks buggy though. Also the tests are way too complex to understand.

2022-07-28 12:10 UTC, nene commented on src/lexer/regexFactory.ts
> +  "''": String.raw`(?:'{escape}*?(?:\\.[^'\\]*)*(?:'|$))+`,
I'm pretty confident this doesn't work as intended.

Let me simplify this regex a bit with additional whitespace and removal of  `:?` optional capture groups:

```
( '{escape}*? (\\.[^'\\]*)* ('|$) )+
```

a) When escapes array contains a single quote `'`, the resulting regex will be:

```
( '[^']*? (\\.[^'\\]*)* ('|$) )+
```

This regex will happily match the following string:

```
'hello\'world'
```

b) When escapes array contains a backslash, the resulting regex will be:

```
( '[^\\]*? (\\.[^'\\]*)* ('|$) )+
```

This regex happily matches the following string:

```
'bla'bla''bla'
```

2022-07-28 12:10 UTC, nene commented on test/trino.test.ts
> +  supportsIdentifiers(format, ['""', '``']);
Trino doesn't support `` `..` `` quoted identifiers.

See the comment in wiki: https://github.com/sql-formatter-org/sql-formatter/wiki/identifiers

2022-07-28 12:10 UTC, nene commented on test/plsql.test.ts
> +      fn (t.id)
I think something has gone wrong with the merge in here.

I moved these two tests inside `supportsJoin()` helper.

2022-08-01 18:50 UTC, inferrinizzard commented
Placing these changes on pause until further notice

2022-08-01 18:50 UTC, closed without merging